<a href="https://colab.research.google.com/github/njonge-nathan/Python_Web_Scraping/blob/main/Python_practice_web_scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# loading the libraries
from bs4 import BeautifulSoup
import requests

In [2]:
url = "https://cytonn.com/blog/article/cytonn-top-employer"

# Make a request to the website.
response = requests.get(url)

# Create a BeautifulSoup object from the response.
soup = BeautifulSoup(response.content, "html.parser")

In [3]:
# Find the table element that you want to scrape.
table = soup.find("table")
print(table)

<table width="600">
<tbody>
<tr>
<td width="49">
<p><strong>RANK</strong></p>
</td>
<td width="220">
<p><strong>COMPANY</strong></p>
</td>
<td width="49">
<p><strong>RANK</strong></p>
</td>
<td width="282">
<p><strong>COMPANY</strong></p>
</td>
</tr>
<tr>
<td width="49">
<p>1</p>
</td>
<td width="220">
<p>SAFARICOM</p>
</td>
<td width="49">
<p>51</p>
</td>
<td width="282">
<p>CELLULANT CORPORATION</p>
</td>
</tr>
<tr>
<td width="49">
<p>2</p>
</td>
<td width="220">
<p>EAST AFRICAN BREWERIES</p>
</td>
<td width="49">
<p>52</p>
</td>
<td width="282">
<p>GENERAL ELECTRIC</p>
</td>
</tr>
<tr>
<td width="49">
<p>3</p>
</td>
<td width="220">
<p>UNITED NATIONS</p>
</td>
<td width="49">
<p>53</p>
</td>
<td width="282">
<p>JUBILEE INSURANCE COMPANY LIMITED</p>
</td>
</tr>
<tr>
<td width="49">
<p>4</p>
</td>
<td width="220">
<p>KCB BANK KENYA LIMITED</p>
</td>
<td width="49">
<p>54</p>
</td>
<td width="282">
<p>UNICEF</p>
</td>
</tr>
<tr>
<td width="49">
<p>5</p>
</td>
<td width="220">
<p>KENYA REVENUE AUTHORITY</p>
</td>
<td width="49">
<p>55</p>
</td>
<td width="282">
<p>USAID</p>
</td>
</tr>
<tr>
<td width="49">
<p>6</p>
</td>
<td width="220">
<p>KENYA PIPELINE COMPANY</p>
</td>
<td width="49">
<p>56</p>
</td>
<td width="282">
<p>GEOTHERMAL DEVELOPMENT COMPANY</p>
</td>
</tr>
<tr>
<td width="49">
<p>7</p>
</td>
<td width="220">
<p>KENGEN</p>
</td>
<td width="49">
<p>57</p>
</td>
<td width="282">
<p>NESTLE</p>
</td>
</tr>
<tr>
<td width="49">
<p>8</p>
</td>
<td width="220">
<p>PRICEWATER HOUSECOOPERS</p>
</td>
<td width="49">
<p>58</p>
</td>
<td width="282">
<p>OXFAM</p>
</td>
</tr>
<tr>
<td width="49">
<p>9</p>
</td>
<td width="220">
<p>COCA-COLA</p>
</td>
<td width="49">
<p>59</p>
</td>
<td width="282">
<p>ORACLE</p>
</td>
</tr>
<tr>
<td width="49">
<p>10</p>
</td>
<td width="220">
<p>KENYA AIRWAYS</p>
</td>
<td width="49">
<p>60</p>
</td>
<td width="282">
<p>CITI BANK</p>
</td>
</tr>
<tr>
<td width="49">
<p>11</p>
</td>
<td width="220">
<p>DELOITTE</p>
</td>
<td width="49">
<p>61</p>
</td>
<td width="282">
<p>P&amp;G</p>
</td>
</tr>
<tr>
<td width="49">
<p>12</p>
</td>
<td width="220">
<p>UNILEVER</p>
</td>
<td width="49">
<p>62</p>
</td>
<td width="282">
<p>DAVIS &amp; SHIRTLIFF</p>
</td>
</tr>
<tr>
<td width="49">
<p>13</p>
</td>
<td width="220">
<p>KPLC</p>
</td>
<td width="49">
<p>63</p>
</td>
<td width="282">
<p>KENYA CO -Â OPERATIVE CREAMERIES LTD</p>
</td>
</tr>
<tr>
<td width="49">
<p>14</p>
</td>
<td width="220">
<p>EQUITY BANK</p>
</td>
<td width="49">
<p>64</p>
</td>
<td width="282">
<p>ILRI</p>
</td>
</tr>
<tr>
<td width="49">
<p>15</p>
</td>
<td width="220">
<p>BRITISH AMERICAN TOBACCO</p>
</td>
<td width="49">
<p>65</p>
</td>
<td width="282">
<p>TUSKYS</p>
</td>
</tr>
<tr>
<td width="49">
<p>16</p>
</td>
<td width="220">
<p>CENTUM INVESTMENTS COMPANY</p>
</td>
<td width="49">
<p>66</p>
</td>
<td width="282">
<p>CIC INSURANCE GROUP</p>
</td>
</tr>
<tr>
<td width="49">
<p>17</p>
</td>
<td width="220">
<p>GOOGLE</p>
</td>
<td width="49">
<p>67</p>
</td>
<td width="282">
<p>THE NAIROBI HOSPITAL</p>
</td>
</tr>
<tr>
<td width="49">
<p>18</p>
</td>
<td width="220">
<p>KENYA PORT AUTHORITY</p>
</td>
<td width="49">
<p>68</p>
</td>
<td width="282">
<p>KTDA</p>
</td>
</tr>
<tr>
<td width="49">
<p>19</p>
</td>
<td width="220">
<p>AIRTEL</p>
</td>
<td width="49">
<p>69</p>
</td>
<td width="282">
<p>ONE ACRE FUND</p>
</td>
</tr>
<tr>
<td width="49">
<p>20</p>
</td>
<td width="220">
<p>BRITAM HOLDINGS LIMITED</p>
</td>
<td width="49">
<p>70</p>
</td>
<td width="282">
<p>UNEP</p>
</td>
</tr>
<tr>
<td width="49">
<p>21</p>
</td>
<td width="220">
<p>CENTRAL BANK OF KENYA</p>
</td>
<td width="49">
<p>71</p>
</td>
<td width="282">
<p>KENYA NATIONAL BUREAU OF STATISTICS</p>
</td>
</tr>
<tr>
<td width="49">
<p>22</p>
</td>
<td width="220">
<p>NATION MEDIA GROUP</p>
</td>
<td width="49">
<p>72</p>
</td>
<td width="282">
<p>TOTAL KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>23</p>
</td>
<td width="220">
<p>ROYAL MEDIA SERVICES LTD</p>
</td>
<td width="49">
<p>73</p>
</td>
<td width="282">
<p>BASE TI TANIUM PORT FACILITY</p>
</td>
</tr>
<tr>
<td width="49">
<p>24</p>
</td>
<td width="220">
<p>BIDCO AFRICA</p>
</td>
<td width="49">
<p>74</p>
</td>
<td width="282">
<p>KENYA MEDICAL SUPPLIES AGENCY</p>
</td>
</tr>
<tr>
<td width="49">
<p>25</p>
</td>
<td width="220">
<p>TOYOTA</p>
</td>
<td width="49">
<p>75</p>
</td>
<td width="282">
<p>SAVE THE CHILDREN KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>26</p>
</td>
<td width="220">
<p>CBA KENYA</p>
</td>
<td width="49">
<p>76</p>
</td>
<td width="282">
<p>KENYA AIRPORTS AUTHORITY</p>
</td>
</tr>
<tr>
<td width="49">
<p><strong>27</strong></p>
</td>
<td width="220">
<p><strong>CYTONN INVESTMENTS</strong></p>
</td>
<td width="49">
<p>77</p>
</td>
<td width="282">
<p>NAIVAS LIMITED</p>
</td>
</tr>
<tr>
<td width="49">
<p>28</p>
</td>
<td width="220">
<p>BAMBURI CEMENT</p>
</td>
<td width="49">
<p>78</p>
</td>
<td width="282">
<p>BOLLORE LOGISTICS KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>29</p>
</td>
<td width="220">
<p>BARCLAYS</p>
</td>
<td width="49">
<p>79</p>
</td>
<td width="282">
<p>DEL MONTE KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>30</p>
</td>
<td width="220">
<p>KENYA RED CROSS</p>
</td>
<td width="49">
<p>80</p>
</td>
<td width="282">
<p>NIC BANK GROUP</p>
</td>
</tr>
<tr>
<td width="49">
<p>31</p>
</td>
<td width="220">
<p>WORLD VISION INTERNATIONAL</p>
</td>
<td width="49">
<p>81</p>
</td>
<td width="282">
<p>BRITISH HIGH COMISSION</p>
</td>
</tr>
<tr>
<td width="49">
<p>32</p>
</td>
<td width="220">
<p>STANDARD CHARTERED</p>
</td>
<td width="49">
<p>82</p>
</td>
<td width="282">
<p>KENYA ELECTRICITY TRANSMISSION COMPANY</p>
</td>
</tr>
<tr>
<td width="49">
<p>33</p>
</td>
<td width="220">
<p>BROOKSIDE DAIRY LIMITED</p>
</td>
<td width="49">
<p>83</p>
</td>
<td width="282">
<p>HUAWEI</p>
</td>
</tr>
<tr>
<td width="49">
<p>34</p>
</td>
<td width="220">
<p>ANDELA KENYA</p>
</td>
<td width="49">
<p>84</p>
</td>
<td width="282">
<p>PLAN INTERNATIONAL KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>35</p>
</td>
<td width="220">
<p>KEMRI</p>
</td>
<td width="49">
<p>85</p>
</td>
<td width="282">
<p>AMIRAN KENYA LIMITED</p>
</td>
</tr>
<tr>
<td width="49">
<p>36</p>
</td>
<td width="220">
<p>MICROSOFT</p>
</td>
<td width="49">
<p>86</p>
</td>
<td width="282">
<p>DT DOBIE</p>
</td>
</tr>
<tr>
<td width="49">
<p>37</p>
</td>
<td width="220">
<p>ISUZU EAST AFRICA LIMITED</p>
</td>
<td width="49">
<p>87</p>
</td>
<td width="282">
<p>KAPA OIL REFINERIES LTD</p>
</td>
</tr>
<tr>
<td width="49">
<p>38</p>
</td>
<td width="220">
<p>KENYA BUREAU OF STANDARDS</p>
</td>
<td width="49">
<p>88</p>
</td>
<td width="282">
<p>SAMSUNG</p>
</td>
</tr>
<tr>
<td width="49">
<p>39</p>
</td>
<td width="220">
<p>GLAXOSMITHKLINE</p>
</td>
<td width="49">
<p>89</p>
</td>
<td width="282">
<p>JAMES FINLAY</p>
</td>
</tr>
<tr>
<td width="49">
<p>40</p>
</td>
<td width="220">
<p>AMREF HEALTH AFRICA</p>
</td>
<td width="49">
<p>90</p>
</td>
<td width="282">
<p>VIVO ENERGY KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>41</p>
</td>
<td width="220">
<p>DHL</p>
</td>
<td width="49">
<p>91</p>
</td>
<td width="282">
<p>BBC</p>
</td>
</tr>
<tr>
<td width="49">
<p>42</p>
</td>
<td width="220">
<p>SPORTPESA</p>
</td>
<td width="49">
<p>92</p>
</td>
<td width="282">
<p>CARREFOUR KENYA</p>
</td>
</tr>
<tr>
<td width="49">
<p>43</p>
</td>
<td width="220">
<p>WORLD BANK</p>
</td>
<td width="49">
<p>93</p>
</td>
<td width="282">
<p>LIQUID TELECOM</p>
</td>
</tr>
<tr>
<td width="49">
<p>44</p>
</td>
<td width="220">
<p>BONFIRE ADVENTURES</p>
</td>
<td width="49">
<p>94</p>
</td>
<td width="282">
<p>ICEA LION GENERAL INSURANCE</p>
</td>
</tr>
<tr>
<td width="49">
<p>45</p>
</td>
<td width="220">
<p>IBM</p>
</td>
<td width="49">
<p>95</p>
</td>
<td width="282">
<p>KENYA SEED COMPANY</p>
</td>
</tr>
<tr>
<td width="49">
<p>46</p>
</td>
<td width="220">
<p>TELKOM KENYA</p>
</td>
<td width="49">
<p>96</p>
</td>
<td width="282">
<p>KENYATTA NATIONAL HOSPITAL</p>
</td>
</tr>
<tr>
<td width="49">
<p>47</p>
</td>
<td width="220">
<p>NHIF</p>
</td>
<td width="49">
<p>97</p>
</td>
<td width="282">
<p>MABATI ROLLING MILLS</p>
</td>
</tr>
<tr>
<td width="49">
<p>48</p>
</td>
<td width="220">
<p>CHANDARIA INDUSTRIES</p>
</td>
<td width="49">
<p>98</p>
</td>
<td width="282">
<p>MOMBASA CEMENT</p>
</td>
</tr>
<tr>
<td width="49">
<p>49</p>
</td>
<td width="220">
<p>JUMIA</p>
</td>
<td width="49">
<p>99</p>
</td>
<td width="282">
<p>KALRO</p>
</td>
</tr>
<tr>
<td width="49">
<p>50</p>
</td>
<td width="220">
<p>ERNST &amp; YOUNG</p>
</td>
<td width="49">
<p>100</p>
</td>
<td width="282">
<p>KEPHIS</p>
</td>
</tr>
</tbody>
</table>

In [4]:
# creating a list of table rows
rows = table.find_all('tr')
print(rows)

[<tr>
<td width="49">
<p><strong>RANK</strong></p>
</td>
<td width="220">
<p><strong>COMPANY</strong></p>
</td>
<td width="49">
<p><strong>RANK</strong></p>
</td>
<td width="282">
<p><strong>COMPANY</strong></p>
</td>
</tr>, <tr>
<td width="49">
<p>1</p>
</td>
<td width="220">
<p>SAFARICOM</p>
</td>
<td width="49">
<p>51</p>
</td>
<td width="282">
<p>CELLULANT CORPORATION</p>
</td>
</tr>, <tr>
<td width="49">
<p>2</p>
</td>
<td width="220">
<p>EAST AFRICAN BREWERIES</p>
</td>
<td width="49">
<p>52</p>
</td>
<td width="282">
<p>GENERAL ELECTRIC</p>
</td>
</tr>, <tr>
<td width="49">
<p>3</p>
</td>
<td width="220">
<p>UNITED NATIONS</p>
</td>
<td width="49">
<p>53</p>
</td>
<td width="282">
<p>JUBILEE INSURANCE COMPANY LIMITED</p>
</td>
</tr>, <tr>
<td width="49">
<p>4</p>
</td>
<td width="220">
<p>KCB BANK KENYA LIMITED</p>
</td>
<td width="49">
<p>54</p>
</td>
<td width="282">
<p>UNICEF</p>
</td>
</tr>, <tr>
<td width="49">
<p>5</p>
</td>
<td width="220">
<p>KENYA REVENUE AUTHORITY</p>
</td>
<td width="49">
<p>55</p>
</td>
<td width="282">
<p>USAID</p>
</td>
</tr>, <tr>
<td width="49">
<p>6</p>
</td>
<td width="220">
<p>KENYA PIPELINE COMPANY</p>
</td>
<td width="49">
<p>56</p>
</td>
<td width="282">
<p>GEOTHERMAL DEVELOPMENT COMPANY</p>
</td>
</tr>, <tr>
<td width="49">
<p>7</p>
</td>
<td width="220">
<p>KENGEN</p>
</td>
<td width="49">
<p>57</p>
</td>
<td width="282">
<p>NESTLE</p>
</td>
</tr>, <tr>
<td width="49">
<p>8</p>
</td>
<td width="220">
<p>PRICEWATER HOUSECOOPERS</p>
</td>
<td width="49">
<p>58</p>
</td>
<td width="282">
<p>OXFAM</p>
</td>
</tr>, <tr>
<td width="49">
<p>9</p>
</td>
<td width="220">
<p>COCA-COLA</p>
</td>
<td width="49">
<p>59</p>
</td>
<td width="282">
<p>ORACLE</p>
</td>
</tr>, <tr>
<td width="49">
<p>10</p>
</td>
<td width="220">
<p>KENYA AIRWAYS</p>
</td>
<td width="49">
<p>60</p>
</td>
<td width="282">
<p>CITI BANK</p>
</td>
</tr>, <tr>
<td width="49">
<p>11</p>
</td>
<td width="220">
<p>DELOITTE</p>
</td>
<td width="49">
<p>61</p>
</td>
<td width="282">
<p>P&amp;G</p>
</td>
</tr>, <tr>
<td width="49">
<p>12</p>
</td>
<td width="220">
<p>UNILEVER</p>
</td>
<td width="49">
<p>62</p>
</td>
<td width="282">
<p>DAVIS &amp; SHIRTLIFF</p>
</td>
</tr>, <tr>
<td width="49">
<p>13</p>
</td>
<td width="220">
<p>KPLC</p>
</td>
<td width="49">
<p>63</p>
</td>
<td width="282">
<p>KENYA CO -Â OPERATIVE CREAMERIES LTD</p>
</td>
</tr>, <tr>
<td width="49">
<p>14</p>
</td>
<td width="220">
<p>EQUITY BANK</p>
</td>
<td width="49">
<p>64</p>
</td>
<td width="282">
<p>ILRI</p>
</td>
</tr>, <tr>
<td width="49">
<p>15</p>
</td>
<td width="220">
<p>BRITISH AMERICAN TOBACCO</p>
</td>
<td width="49">
<p>65</p>
</td>
<td width="282">
<p>TUSKYS</p>
</td>
</tr>, <tr>
<td width="49">
<p>16</p>
</td>
<td width="220">
<p>CENTUM INVESTMENTS COMPANY</p>
</td>
<td width="49">
<p>66</p>
</td>
<td width="282">
<p>CIC INSURANCE GROUP</p>
</td>
</tr>, <tr>
<td width="49">
<p>17</p>
</td>
<td width="220">
<p>GOOGLE</p>
</td>
<td width="49">
<p>67</p>
</td>
<td width="282">
<p>THE NAIROBI HOSPITAL</p>
</td>
</tr>, <tr>
<td width="49">
<p>18</p>
</td>
<td width="220">
<p>KENYA PORT AUTHORITY</p>
</td>
<td width="49">
<p>68</p>
</td>
<td width="282">
<p>KTDA</p>
</td>
</tr>, <tr>
<td width="49">
<p>19</p>
</td>
<td width="220">
<p>AIRTEL</p>
</td>
<td width="49">
<p>69</p>
</td>
<td width="282">
<p>ONE ACRE FUND</p>
</td>
</tr>, <tr>
<td width="49">
<p>20</p>
</td>
<td width="220">
<p>BRITAM HOLDINGS LIMITED</p>
</td>
<td width="49">
<p>70</p>
</td>
<td width="282">
<p>UNEP</p>
</td>
</tr>, <tr>
<td width="49">
<p>21</p>
</td>
<td width="220">
<p>CENTRAL BANK OF KENYA</p>
</td>
<td width="49">
<p>71</p>
</td>
<td width="282">
<p>KENYA NATIONAL BUREAU OF STATISTICS</p>
</td>
</tr>, <tr>
<td width="49">
<p>22</p>
</td>
<td width="220">
<p>NATION MEDIA GROUP</p>
</td>
<td width="49">
<p>72</p>
</td>
<td width="282">
<p>TOTAL KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>23</p>
</td>
<td width="220">
<p>ROYAL MEDIA SERVICES LTD</p>
</td>
<td width="49">
<p>73</p>
</td>
<td width="282">
<p>BASE TI TANIUM PORT FACILITY</p>
</td>
</tr>, <tr>
<td width="49">
<p>24</p>
</td>
<td width="220">
<p>BIDCO AFRICA</p>
</td>
<td width="49">
<p>74</p>
</td>
<td width="282">
<p>KENYA MEDICAL SUPPLIES AGENCY</p>
</td>
</tr>, <tr>
<td width="49">
<p>25</p>
</td>
<td width="220">
<p>TOYOTA</p>
</td>
<td width="49">
<p>75</p>
</td>
<td width="282">
<p>SAVE THE CHILDREN KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>26</p>
</td>
<td width="220">
<p>CBA KENYA</p>
</td>
<td width="49">
<p>76</p>
</td>
<td width="282">
<p>KENYA AIRPORTS AUTHORITY</p>
</td>
</tr>, <tr>
<td width="49">
<p><strong>27</strong></p>
</td>
<td width="220">
<p><strong>CYTONN INVESTMENTS</strong></p>
</td>
<td width="49">
<p>77</p>
</td>
<td width="282">
<p>NAIVAS LIMITED</p>
</td>
</tr>, <tr>
<td width="49">
<p>28</p>
</td>
<td width="220">
<p>BAMBURI CEMENT</p>
</td>
<td width="49">
<p>78</p>
</td>
<td width="282">
<p>BOLLORE LOGISTICS KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>29</p>
</td>
<td width="220">
<p>BARCLAYS</p>
</td>
<td width="49">
<p>79</p>
</td>
<td width="282">
<p>DEL MONTE KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>30</p>
</td>
<td width="220">
<p>KENYA RED CROSS</p>
</td>
<td width="49">
<p>80</p>
</td>
<td width="282">
<p>NIC BANK GROUP</p>
</td>
</tr>, <tr>
<td width="49">
<p>31</p>
</td>
<td width="220">
<p>WORLD VISION INTERNATIONAL</p>
</td>
<td width="49">
<p>81</p>
</td>
<td width="282">
<p>BRITISH HIGH COMISSION</p>
</td>
</tr>, <tr>
<td width="49">
<p>32</p>
</td>
<td width="220">
<p>STANDARD CHARTERED</p>
</td>
<td width="49">
<p>82</p>
</td>
<td width="282">
<p>KENYA ELECTRICITY TRANSMISSION COMPANY</p>
</td>
</tr>, <tr>
<td width="49">
<p>33</p>
</td>
<td width="220">
<p>BROOKSIDE DAIRY LIMITED</p>
</td>
<td width="49">
<p>83</p>
</td>
<td width="282">
<p>HUAWEI</p>
</td>
</tr>, <tr>
<td width="49">
<p>34</p>
</td>
<td width="220">
<p>ANDELA KENYA</p>
</td>
<td width="49">
<p>84</p>
</td>
<td width="282">
<p>PLAN INTERNATIONAL KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>35</p>
</td>
<td width="220">
<p>KEMRI</p>
</td>
<td width="49">
<p>85</p>
</td>
<td width="282">
<p>AMIRAN KENYA LIMITED</p>
</td>
</tr>, <tr>
<td width="49">
<p>36</p>
</td>
<td width="220">
<p>MICROSOFT</p>
</td>
<td width="49">
<p>86</p>
</td>
<td width="282">
<p>DT DOBIE</p>
</td>
</tr>, <tr>
<td width="49">
<p>37</p>
</td>
<td width="220">
<p>ISUZU EAST AFRICA LIMITED</p>
</td>
<td width="49">
<p>87</p>
</td>
<td width="282">
<p>KAPA OIL REFINERIES LTD</p>
</td>
</tr>, <tr>
<td width="49">
<p>38</p>
</td>
<td width="220">
<p>KENYA BUREAU OF STANDARDS</p>
</td>
<td width="49">
<p>88</p>
</td>
<td width="282">
<p>SAMSUNG</p>
</td>
</tr>, <tr>
<td width="49">
<p>39</p>
</td>
<td width="220">
<p>GLAXOSMITHKLINE</p>
</td>
<td width="49">
<p>89</p>
</td>
<td width="282">
<p>JAMES FINLAY</p>
</td>
</tr>, <tr>
<td width="49">
<p>40</p>
</td>
<td width="220">
<p>AMREF HEALTH AFRICA</p>
</td>
<td width="49">
<p>90</p>
</td>
<td width="282">
<p>VIVO ENERGY KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>41</p>
</td>
<td width="220">
<p>DHL</p>
</td>
<td width="49">
<p>91</p>
</td>
<td width="282">
<p>BBC</p>
</td>
</tr>, <tr>
<td width="49">
<p>42</p>
</td>
<td width="220">
<p>SPORTPESA</p>
</td>
<td width="49">
<p>92</p>
</td>
<td width="282">
<p>CARREFOUR KENYA</p>
</td>
</tr>, <tr>
<td width="49">
<p>43</p>
</td>
<td width="220">
<p>WORLD BANK</p>
</td>
<td width="49">
<p>93</p>
</td>
<td width="282">
<p>LIQUID TELECOM</p>
</td>
</tr>, <tr>
<td width="49">
<p>44</p>
</td>
<td width="220">
<p>BONFIRE ADVENTURES</p>
</td>
<td width="49">
<p>94</p>
</td>
<td width="282">
<p>ICEA LION GENERAL INSURANCE</p>
</td>
</tr>, <tr>
<td width="49">
<p>45</p>
</td>
<td width="220">
<p>IBM</p>
</td>
<td width="49">
<p>95</p>
</td>
<td width="282">
<p>KENYA SEED COMPANY</p>
</td>
</tr>, <tr>
<td width="49">
<p>46</p>
</td>
<td width="220">
<p>TELKOM KENYA</p>
</td>
<td width="49">
<p>96</p>
</td>
<td width="282">
<p>KENYATTA NATIONAL HOSPITAL</p>
</td>
</tr>, <tr>
<td width="49">
<p>47</p>
</td>
<td width="220">
<p>NHIF</p>
</td>
<td width="49">
<p>97</p>
</td>
<td width="282">
<p>MABATI ROLLING MILLS</p>
</td>
</tr>, <tr>
<td width="49">
<p>48</p>
</td>
<td width="220">
<p>CHANDARIA INDUSTRIES</p>
</td>
<td width="49">
<p>98</p>
</td>
<td width="282">
<p>MOMBASA CEMENT</p>
</td>
</tr>, <tr>
<td width="49">
<p>49</p>
</td>
<td width="220">
<p>JUMIA</p>
</td>
<td width="49">
<p>99</p>
</td>
<td width="282">
<p>KALRO</p>
</td>
</tr>, <tr>
<td width="49">
<p>50</p>
</td>
<td width="220">
<p>ERNST &amp; YOUNG</p>
</td>
<td width="49">
<p>100</p>
</td>
<td width="282">
<p>KEPHIS</p>
</td>
</tr>]

In [5]:
# create a list of table columns
columns = []
for row in rows:
    columns.append(row.find_all('td'))
print(columns)

[[<td width="49">
<p><strong>RANK</strong></p>
</td>, <td width="220">
<p><strong>COMPANY</strong></p>
</td>, <td width="49">
<p><strong>RANK</strong></p>
</td>, <td width="282">
<p><strong>COMPANY</strong></p>
</td>], [<td width="49">
<p>1</p>
</td>, <td width="220">
<p>SAFARICOM</p>
</td>, <td width="49">
<p>51</p>
</td>, <td width="282">
<p>CELLULANT CORPORATION</p>
</td>], [<td width="49">
<p>2</p>
</td>, <td width="220">
<p>EAST AFRICAN BREWERIES</p>
</td>, <td width="49">
<p>52</p>
</td>, <td width="282">
<p>GENERAL ELECTRIC</p>
</td>], [<td width="49">
<p>3</p>
</td>, <td width="220">
<p>UNITED NATIONS</p>
</td>, <td width="49">
<p>53</p>
</td>, <td width="282">
<p>JUBILEE INSURANCE COMPANY LIMITED</p>
</td>], [<td width="49">
<p>4</p>
</td>, <td width="220">
<p>KCB BANK KENYA LIMITED</p>
</td>, <td width="49">
<p>54</p>
</td>, <td width="282">
<p>UNICEF</p>
</td>], [<td width="49">
<p>5</p>
</td>, <td width="220">
<p>KENYA REVENUE AUTHORITY</p>
</td>, <td width="49">
<p>55</p>
</td>, <td width="282">
<p>USAID</p>
</td>], [<td width="49">
<p>6</p>
</td>, <td width="220">
<p>KENYA PIPELINE COMPANY</p>
</td>, <td width="49">
<p>56</p>
</td>, <td width="282">
<p>GEOTHERMAL DEVELOPMENT COMPANY</p>
</td>], [<td width="49">
<p>7</p>
</td>, <td width="220">
<p>KENGEN</p>
</td>, <td width="49">
<p>57</p>
</td>, <td width="282">
<p>NESTLE</p>
</td>], [<td width="49">
<p>8</p>
</td>, <td width="220">
<p>PRICEWATER HOUSECOOPERS</p>
</td>, <td width="49">
<p>58</p>
</td>, <td width="282">
<p>OXFAM</p>
</td>], [<td width="49">
<p>9</p>
</td>, <td width="220">
<p>COCA-COLA</p>
</td>, <td width="49">
<p>59</p>
</td>, <td width="282">
<p>ORACLE</p>
</td>], [<td width="49">
<p>10</p>
</td>, <td width="220">
<p>KENYA AIRWAYS</p>
</td>, <td width="49">
<p>60</p>
</td>, <td width="282">
<p>CITI BANK</p>
</td>], [<td width="49">
<p>11</p>
</td>, <td width="220">
<p>DELOITTE</p>
</td>, <td width="49">
<p>61</p>
</td>, <td width="282">
<p>P&amp;G</p>
</td>], [<td width="49">
<p>12</p>
</td>, <td width="220">
<p>UNILEVER</p>
</td>, <td width="49">
<p>62</p>
</td>, <td width="282">
<p>DAVIS &amp; SHIRTLIFF</p>
</td>], [<td width="49">
<p>13</p>
</td>, <td width="220">
<p>KPLC</p>
</td>, <td width="49">
<p>63</p>
</td>, <td width="282">
<p>KENYA CO -Â OPERATIVE CREAMERIES LTD</p>
</td>], [<td width="49">
<p>14</p>
</td>, <td width="220">
<p>EQUITY BANK</p>
</td>, <td width="49">
<p>64</p>
</td>, <td width="282">
<p>ILRI</p>
</td>], [<td width="49">
<p>15</p>
</td>, <td width="220">
<p>BRITISH AMERICAN TOBACCO</p>
</td>, <td width="49">
<p>65</p>
</td>, <td width="282">
<p>TUSKYS</p>
</td>], [<td width="49">
<p>16</p>
</td>, <td width="220">
<p>CENTUM INVESTMENTS COMPANY</p>
</td>, <td width="49">
<p>66</p>
</td>, <td width="282">
<p>CIC INSURANCE GROUP</p>
</td>], [<td width="49">
<p>17</p>
</td>, <td width="220">
<p>GOOGLE</p>
</td>, <td width="49">
<p>67</p>
</td>, <td width="282">
<p>THE NAIROBI HOSPITAL</p>
</td>], [<td width="49">
<p>18</p>
</td>, <td width="220">
<p>KENYA PORT AUTHORITY</p>
</td>, <td width="49">
<p>68</p>
</td>, <td width="282">
<p>KTDA</p>
</td>], [<td width="49">
<p>19</p>
</td>, <td width="220">
<p>AIRTEL</p>
</td>, <td width="49">
<p>69</p>
</td>, <td width="282">
<p>ONE ACRE FUND</p>
</td>], [<td width="49">
<p>20</p>
</td>, <td width="220">
<p>BRITAM HOLDINGS LIMITED</p>
</td>, <td width="49">
<p>70</p>
</td>, <td width="282">
<p>UNEP</p>
</td>], [<td width="49">
<p>21</p>
</td>, <td width="220">
<p>CENTRAL BANK OF KENYA</p>
</td>, <td width="49">
<p>71</p>
</td>, <td width="282">
<p>KENYA NATIONAL BUREAU OF STATISTICS</p>
</td>], [<td width="49">
<p>22</p>
</td>, <td width="220">
<p>NATION MEDIA GROUP</p>
</td>, <td width="49">
<p>72</p>
</td>, <td width="282">
<p>TOTAL KENYA</p>
</td>], [<td width="49">
<p>23</p>
</td>, <td width="220">
<p>ROYAL MEDIA SERVICES LTD</p>
</td>, <td width="49">
<p>73</p>
</td>, <td width="282">
<p>BASE TI TANIUM PORT FACILITY</p>
</td>], [<td width="49">
<p>24</p>
</td>, <td width="220">
<p>BIDCO AFRICA</p>
</td>, <td width="49">
<p>74</p>
</td>, <td width="282">
<p>KENYA MEDICAL SUPPLIES AGENCY</p>
</td>], [<td width="49">
<p>25</p>
</td>, <td width="220">
<p>TOYOTA</p>
</td>, <td width="49">
<p>75</p>
</td>, <td width="282">
<p>SAVE THE CHILDREN KENYA</p>
</td>], [<td width="49">
<p>26</p>
</td>, <td width="220">
<p>CBA KENYA</p>
</td>, <td width="49">
<p>76</p>
</td>, <td width="282">
<p>KENYA AIRPORTS AUTHORITY</p>
</td>], [<td width="49">
<p><strong>27</strong></p>
</td>, <td width="220">
<p><strong>CYTONN INVESTMENTS</strong></p>
</td>, <td width="49">
<p>77</p>
</td>, <td width="282">
<p>NAIVAS LIMITED</p>
</td>], [<td width="49">
<p>28</p>
</td>, <td width="220">
<p>BAMBURI CEMENT</p>
</td>, <td width="49">
<p>78</p>
</td>, <td width="282">
<p>BOLLORE LOGISTICS KENYA</p>
</td>], [<td width="49">
<p>29</p>
</td>, <td width="220">
<p>BARCLAYS</p>
</td>, <td width="49">
<p>79</p>
</td>, <td width="282">
<p>DEL MONTE KENYA</p>
</td>], [<td width="49">
<p>30</p>
</td>, <td width="220">
<p>KENYA RED CROSS</p>
</td>, <td width="49">
<p>80</p>
</td>, <td width="282">
<p>NIC BANK GROUP</p>
</td>], [<td width="49">
<p>31</p>
</td>, <td width="220">
<p>WORLD VISION INTERNATIONAL</p>
</td>, <td width="49">
<p>81</p>
</td>, <td width="282">
<p>BRITISH HIGH COMISSION</p>
</td>], [<td width="49">
<p>32</p>
</td>, <td width="220">
<p>STANDARD CHARTERED</p>
</td>, <td width="49">
<p>82</p>
</td>, <td width="282">
<p>KENYA ELECTRICITY TRANSMISSION COMPANY</p>
</td>], [<td width="49">
<p>33</p>
</td>, <td width="220">
<p>BROOKSIDE DAIRY LIMITED</p>
</td>, <td width="49">
<p>83</p>
</td>, <td width="282">
<p>HUAWEI</p>
</td>], [<td width="49">
<p>34</p>
</td>, <td width="220">
<p>ANDELA KENYA</p>
</td>, <td width="49">
<p>84</p>
</td>, <td width="282">
<p>PLAN INTERNATIONAL KENYA</p>
</td>], [<td width="49">
<p>35</p>
</td>, <td width="220">
<p>KEMRI</p>
</td>, <td width="49">
<p>85</p>
</td>, <td width="282">
<p>AMIRAN KENYA LIMITED</p>
</td>], [<td width="49">
<p>36</p>
</td>, <td width="220">
<p>MICROSOFT</p>
</td>, <td width="49">
<p>86</p>
</td>, <td width="282">
<p>DT DOBIE</p>
</td>], [<td width="49">
<p>37</p>
</td>, <td width="220">
<p>ISUZU EAST AFRICA LIMITED</p>
</td>, <td width="49">
<p>87</p>
</td>, <td width="282">
<p>KAPA OIL REFINERIES LTD</p>
</td>], [<td width="49">
<p>38</p>
</td>, <td width="220">
<p>KENYA BUREAU OF STANDARDS</p>
</td>, <td width="49">
<p>88</p>
</td>, <td width="282">
<p>SAMSUNG</p>
</td>], [<td width="49">
<p>39</p>
</td>, <td width="220">
<p>GLAXOSMITHKLINE</p>
</td>, <td width="49">
<p>89</p>
</td>, <td width="282">
<p>JAMES FINLAY</p>
</td>], [<td width="49">
<p>40</p>
</td>, <td width="220">
<p>AMREF HEALTH AFRICA</p>
</td>, <td width="49">
<p>90</p>
</td>, <td width="282">
<p>VIVO ENERGY KENYA</p>
</td>], [<td width="49">
<p>41</p>
</td>, <td width="220">
<p>DHL</p>
</td>, <td width="49">
<p>91</p>
</td>, <td width="282">
<p>BBC</p>
</td>], [<td width="49">
<p>42</p>
</td>, <td width="220">
<p>SPORTPESA</p>
</td>, <td width="49">
<p>92</p>
</td>, <td width="282">
<p>CARREFOUR KENYA</p>
</td>], [<td width="49">
<p>43</p>
</td>, <td width="220">
<p>WORLD BANK</p>
</td>, <td width="49">
<p>93</p>
</td>, <td width="282">
<p>LIQUID TELECOM</p>
</td>], [<td width="49">
<p>44</p>
</td>, <td width="220">
<p>BONFIRE ADVENTURES</p>
</td>, <td width="49">
<p>94</p>
</td>, <td width="282">
<p>ICEA LION GENERAL INSURANCE</p>
</td>], [<td width="49">
<p>45</p>
</td>, <td width="220">
<p>IBM</p>
</td>, <td width="49">
<p>95</p>
</td>, <td width="282">
<p>KENYA SEED COMPANY</p>
</td>], [<td width="49">
<p>46</p>
</td>, <td width="220">
<p>TELKOM KENYA</p>
</td>, <td width="49">
<p>96</p>
</td>, <td width="282">
<p>KENYATTA NATIONAL HOSPITAL</p>
</td>], [<td width="49">
<p>47</p>
</td>, <td width="220">
<p>NHIF</p>
</td>, <td width="49">
<p>97</p>
</td>, <td width="282">
<p>MABATI ROLLING MILLS</p>
</td>], [<td width="49">
<p>48</p>
</td>, <td width="220">
<p>CHANDARIA INDUSTRIES</p>
</td>, <td width="49">
<p>98</p>
</td>, <td width="282">
<p>MOMBASA CEMENT</p>
</td>], [<td width="49">
<p>49</p>
</td>, <td width="220">
<p>JUMIA</p>
</td>, <td width="49">
<p>99</p>
</td>, <td width="282">
<p>KALRO</p>
</td>], [<td width="49">
<p>50</p>
</td>, <td width="220">
<p>ERNST &amp; YOUNG</p>
</td>, <td width="49">
<p>100</p>
</td>, <td width="282">
<p>KEPHIS</p>
</td>]]

In [6]:
import pandas as pd

df = pd.DataFrame(columns, columns=['Rank', 'Company','Rank','Company'])
df.head()

,Rank,Company,Rank,Company
0,"[\n, [[RANK]], \n]","[\n, [[COMPANY]], \n]","[\n, [[RANK]], \n]","[\n, [[COMPANY]], \n]"
1,"[\n, [1], \n]","[\n, [SAFARICOM], \n]","[\n, [51], \n]","[\n, [CELLULANT CORPORATION], \n]"
2,"[\n, [2], \n]","[\n, [EAST AFRICAN BREWERIES], \n]","[\n, [52], \n]","[\n, [GENERAL ELECTRIC], \n]"
3,"[\n, [3], \n]","[\n, [UNITED NATIONS], \n]","[\n, [53], \n]","[\n, [JUBILEE INSURANCE COMPANY LIMITED], \n]"
4,"[\n, [4], \n]","[\n, [KCB BANK KENYA LIMITED], \n]","[\n, [54], \n]","[\n, [UNICEF], \n]"

In [7]:
# Drop the first row
df = df.drop(df.index[0])

# Print the DataFrame
print(df)

                Rank                                 Company             Rank  \
1      [\n, [1], \n]                   [\n, [SAFARICOM], \n]   [\n, [51], \n]
2      [\n, [2], \n]      [\n, [EAST AFRICAN BREWERIES], \n]   [\n, [52], \n]
3      [\n, [3], \n]              [\n, [UNITED NATIONS], \n]   [\n, [53], \n]
4      [\n, [4], \n]      [\n, [KCB BANK KENYA LIMITED], \n]   [\n, [54], \n]
5      [\n, [5], \n]     [\n, [KENYA REVENUE AUTHORITY], \n]   [\n, [55], \n]
6      [\n, [6], \n]      [\n, [KENYA PIPELINE COMPANY], \n]   [\n, [56], \n]
7      [\n, [7], \n]                      [\n, [KENGEN], \n]   [\n, [57], \n]
8      [\n, [8], \n]     [\n, [PRICEWATER HOUSECOOPERS], \n]   [\n, [58], \n]
9      [\n, [9], \n]                   [\n, [COCA-COLA], \n]   [\n, [59], \n]
10    [\n, [10], \n]               [\n, [KENYA AIRWAYS], \n]   [\n, [60], \n]
11    [\n, [11], \n]                    [\n, [DELOITTE], \n]   [\n, [61], \n]
12    [\n, [12], \n]                    [\n, [UNILEVER], \n]   [\n, [62], \n]
13    [\n, [13], \n]                        [\n, [KPLC], \n]   [\n, [63], \n]
14    [\n, [14], \n]                 [\n, [EQUITY BANK], \n]   [\n, [64], \n]
15    [\n, [15], \n]    [\n, [BRITISH AMERICAN TOBACCO], \n]   [\n, [65], \n]
16    [\n, [16], \n]  [\n, [CENTUM INVESTMENTS COMPANY], \n]   [\n, [66], \n]
17    [\n, [17], \n]                      [\n, [GOOGLE], \n]   [\n, [67], \n]
18    [\n, [18], \n]        [\n, [KENYA PORT AUTHORITY], \n]   [\n, [68], \n]
19    [\n, [19], \n]                      [\n, [AIRTEL], \n]   [\n, [69], \n]
20    [\n, [20], \n]     [\n, [BRITAM HOLDINGS LIMITED], \n]   [\n, [70], \n]
21    [\n, [21], \n]       [\n, [CENTRAL BANK OF KENYA], \n]   [\n, [71], \n]
22    [\n, [22], \n]          [\n, [NATION MEDIA GROUP], \n]   [\n, [72], \n]
23    [\n, [23], \n]    [\n, [ROYAL MEDIA SERVICES LTD], \n]   [\n, [73], \n]
24    [\n, [24], \n]                [\n, [BIDCO AFRICA], \n]   [\n, [74], \n]
25    [\n, [25], \n]                      [\n, [TOYOTA], \n]   [\n, [75], \n]
26    [\n, [26], \n]                   [\n, [CBA KENYA], \n]   [\n, [76], \n]
27  [\n, [[27]], \n]        [\n, [[CYTONN INVESTMENTS]], \n]   [\n, [77], \n]
28    [\n, [28], \n]              [\n, [BAMBURI CEMENT], \n]   [\n, [78], \n]
29    [\n, [29], \n]                    [\n, [BARCLAYS], \n]   [\n, [79], \n]
30    [\n, [30], \n]             [\n, [KENYA RED CROSS], \n]   [\n, [80], \n]
31    [\n, [31], \n]  [\n, [WORLD VISION INTERNATIONAL], \n]   [\n, [81], \n]
32    [\n, [32], \n]          [\n, [STANDARD CHARTERED], \n]   [\n, [82], \n]
33    [\n, [33], \n]     [\n, [BROOKSIDE DAIRY LIMITED], \n]   [\n, [83], \n]
34    [\n, [34], \n]                [\n, [ANDELA KENYA], \n]   [\n, [84], \n]
35    [\n, [35], \n]                       [\n, [KEMRI], \n]   [\n, [85], \n]
36    [\n, [36], \n]                   [\n, [MICROSOFT], \n]   [\n, [86], \n]
37    [\n, [37], \n]   [\n, [ISUZU EAST AFRICA LIMITED], \n]   [\n, [87], \n]
38    [\n, [38], \n]   [\n, [KENYA BUREAU OF STANDARDS], \n]   [\n, [88], \n]
39    [\n, [39], \n]             [\n, [GLAXOSMITHKLINE], \n]   [\n, [89], \n]
40    [\n, [40], \n]         [\n, [AMREF HEALTH AFRICA], \n]   [\n, [90], \n]
41    [\n, [41], \n]                         [\n, [DHL], \n]   [\n, [91], \n]
42    [\n, [42], \n]                   [\n, [SPORTPESA], \n]   [\n, [92], \n]
43    [\n, [43], \n]                  [\n, [WORLD BANK], \n]   [\n, [93], \n]
44    [\n, [44], \n]          [\n, [BONFIRE ADVENTURES], \n]   [\n, [94], \n]
45    [\n, [45], \n]                         [\n, [IBM], \n]   [\n, [95], \n]
46    [\n, [46], \n]                [\n, [TELKOM KENYA], \n]   [\n, [96], \n]
47    [\n, [47], \n]                        [\n, [NHIF], \n]   [\n, [97], \n]
48    [\n, [48], \n]        [\n, [CHANDARIA INDUSTRIES], \n]   [\n, [98], \n]
49    [\n, [49], \n]                       [\n, [JUMIA], \n]   [\n, [99], \n]
50    [\n, [50], \n]               [\n, [ERNST & YOUNG], \n]  [\n, [100], \n]

                                              Company
1                   [\n, [CELLULANT CORPORATION], \n]
2                        [\n, [GENERAL ELECTRIC], \n]
3       [\n, [JUBILEE INSURANCE COMPANY LIMITED], \n]
4                                  [\n, [UNICEF], \n]
5                                   [\n, [USAID], \n]
6          [\n, [GEOTHERMAL DEVELOPMENT COMPANY], \n]
7                                  [\n, [NESTLE], \n]
8                                   [\n, [OXFAM], \n]
9                                  [\n, [ORACLE], \n]
10                              [\n, [CITI BANK], \n]
11                                    [\n, [P&G], \n]
12                      [\n, [DAVIS & SHIRTLIFF], \n]
13    [\n, [KENYA CO -Â OPERATIVE CREAMERIES LTD], \n]
14                                   [\n, [ILRI], \n]
15                                 [\n, [TUSKYS], \n]
16                    [\n, [CIC INSURANCE GROUP], \n]
17                   [\n, [THE NAIROBI HOSPITAL], \n]
18                                   [\n, [KTDA], \n]
19                          [\n, [ONE ACRE FUND], \n]
20                                   [\n, [UNEP], \n]
21    [\n, [KENYA NATIONAL BUREAU OF STATISTICS], \n]
22                            [\n, [TOTAL KENYA], \n]
23           [\n, [BASE TI TANIUM PORT FACILITY], \n]
24          [\n, [KENYA MEDICAL SUPPLIES AGENCY], \n]
25                [\n, [SAVE THE CHILDREN KENYA], \n]
26               [\n, [KENYA AIRPORTS AUTHORITY], \n]
27                         [\n, [NAIVAS LIMITED], \n]
28                [\n, [BOLLORE LOGISTICS KENYA], \n]
29                        [\n, [DEL MONTE KENYA], \n]
30                         [\n, [NIC BANK GROUP], \n]
31                 [\n, [BRITISH HIGH COMISSION], \n]
32  [\n, [KENYA ELECTRICITY TRANSMISSION COMPANY],...
33                                 [\n, [HUAWEI], \n]
34               [\n, [PLAN INTERNATIONAL KENYA], \n]
35                   [\n, [AMIRAN KENYA LIMITED], \n]
36                               [\n, [DT DOBIE], \n]
37                [\n, [KAPA OIL REFINERIES LTD], \n]
38                                [\n, [SAMSUNG], \n]
39                           [\n, [JAMES FINLAY], \n]
40                      [\n, [VIVO ENERGY KENYA], \n]
41                                    [\n, [BBC], \n]
42                        [\n, [CARREFOUR KENYA], \n]
43                         [\n, [LIQUID TELECOM], \n]
44            [\n, [ICEA LION GENERAL INSURANCE], \n]
45                     [\n, [KENYA SEED COMPANY], \n]
46             [\n, [KENYATTA NATIONAL HOSPITAL], \n]
47                   [\n, [MABATI ROLLING MILLS], \n]
48                         [\n, [MOMBASA CEMENT], \n]
49                                  [\n, [KALRO], \n]
50                                 [\n, [KEPHIS], \n]

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rank     50 non-null     object
 1   Company  50 non-null     object
 2   Rank     50 non-null     object
 3   Company  50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [9]:
# Convert the 'Rank' and 'Company' columns to a string dtype
df['Rank'] = df['Rank'].astype(str)
df['Company'] = df['Company'].astype(str)
df['Rank'] = df['Rank'].astype(str)
df['Company'] = df['Company'].astype(str)

In [10]:
# Rename one of the duplicate columns
df = df.rename(columns={'Rank2': 'Company2'})

# Print the DataFrame
df.head()

,Rank,Company,Rank,Company
1,"<td width=""49"">\n<p>1</p>\n</td>","<td width=""220"">\n<p>SAFARICOM</p>\n</td>","<td width=""49"">\n<p>51</p>\n</td>","<td width=""282"">\n<p>CELLULANT CORPORATION</p>..."
2,"<td width=""49"">\n<p>2</p>\n</td>","<td width=""220"">\n<p>EAST AFRICAN BREWERIES</p...","<td width=""49"">\n<p>52</p>\n</td>","<td width=""282"">\n<p>GENERAL ELECTRIC</p>\n</td>"
3,"<td width=""49"">\n<p>3</p>\n</td>","<td width=""220"">\n<p>UNITED NATIONS</p>\n</td>","<td width=""49"">\n<p>53</p>\n</td>","<td width=""282"">\n<p>JUBILEE INSURANCE COMPANY..."
4,"<td width=""49"">\n<p>4</p>\n</td>","<td width=""220"">\n<p>KCB BANK KENYA LIMITED</p...","<td width=""49"">\n<p>54</p>\n</td>","<td width=""282"">\n<p>UNICEF</p>\n</td>"
5,"<td width=""49"">\n<p>5</p>\n</td>","<td width=""220"">\n<p>KENYA REVENUE AUTHORITY</...","<td width=""49"">\n<p>55</p>\n</td>","<td width=""282"">\n<p>USAID</p>\n</td>"

In [11]:
# Remove the HTML tags
df = df.replace(r"<[^>]*>", "", regex=True)

# Strip whitespace
df = df.applymap(lambda x: x.strip())

# Standardize the case
df = df.applymap(lambda x: x.upper())

# Convert data types
df["Rank"] = df["Rank"].astype(int)
df["Rank"] = df["Rank"].astype(int)

# Remove empty cells
df = df.dropna()

# Remove duplicates
df = df.drop_duplicates()

# Print the cleaned data
df.head()

   Rank                  Company  Rank                            Company
1     1                SAFARICOM    51              CELLULANT CORPORATION
2     2   EAST AFRICAN BREWERIES    52                   GENERAL ELECTRIC
3     3           UNITED NATIONS    53  JUBILEE INSURANCE COMPANY LIMITED
4     4   KCB BANK KENYA LIMITED    54                             UNICEF
5     5  KENYA REVENUE AUTHORITY    55                              USAID

In [12]:
# export the data to a clean excel file
df.to_csv('company_scraped.csv', index=False)

df.to_excel("company_scraped.xlsx", index=False)